// 🎭 МОКОВЫЕ ДАННЫЕ
// Используются когда USE_BACKEND = false

import type { User, Category, Subcategory, Product, Courier } from "@/types"

export const MOCK_USERS: User[] = [
  {
    id: "1",
    login: "manager",
    password: "manager123",
    role: "manager",
  },
  {
    id: "2",
    login: "courier1",
    password: "courier123",
    role: "courier",
    cities: ["Bocholt", "Köln"],
  },
]

export const MOCK_CATEGORIES: Category[] = [
  { id: "1", name: "Электроника", description: "Электронные товары" },
  { id: "2", name: "Одежда", description: "Одежда и аксессуары" },
]

export const MOCK_SUBCATEGORIES: Subcategory[] = [
  { id: "1", name: "Смартфоны", categoryId: "1", description: "Мобильные телефоны" },
  { id: "2", name: "Ноутбуки", categoryId: "1", description: "Портативные компьютеры" },
]

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "iPhone 15",
    description: "Новый iPhone",
    price: 999,
    categoryId: "1",
    subcategoryId: "1",
    imageUrl: "/placeholder.svg",
    courierQuantities: { "2": 5 },
  },
]

export const MOCK_COURIERS: Courier[] = [
  {
    id: "2",
    login: "courier1",
    password: "courier123",
    cities: ["Bocholt", "Köln"],
  },
]

export const MOCK_CITIES = [
  "Berlin",
  "Hamburg",
  "München",
  "Köln",
  "Frankfurt",
  "Stuttgart",
  "Düsseldorf",
  "Dortmund",
  "Essen",
  "Leipzig",
  "Bremen",
  "Dresden",
  "Hannover",
  "Nürnberg",
  "Duisburg",
  "Bochum",
  "Wuppertal",
  "Bielefeld",
  "Bonn",
  "Münster",
  "Karlsruhe",
  "Mannheim",
  "Augsburg",
  "Wiesbaden",
  "Gelsenkirchen",
  "Mönchengladbach",
  "Braunschweig",
  "Chemnitz",
  "Kiel",
  "Aachen",
  "Halle",
  "Magdeburg",
  "Freiburg",
  "Krefeld",
  "Lübeck",
  "Oberhausen",
  "Erfurt",
  "Mainz",
  "Rostock",
  "Kassel",
  "Hagen",
  "Hamm",
  "Saarbrücken",
  "Mülheim",
  "Potsdam",
  "Ludwigshafen",
  "Oldenburg",
  "Leverkusen",
  "Osnabrück",
  "Solingen",
  "Heidelberg",
  "Herne",
  "Neuss",
  "Darmstadt",
  "Paderborn",
  "Regensburg",
  "Ingolstadt",
  "Würzburg",
  "Fürth",
  "Wolfsburg",
  "Offenbach",
  "Ulm",
  "Heilbronn",
  "Pforzheim",
  "Göttingen",
  "Bottrop",
  "Trier",
  "Recklinghausen",
  "Reutlingen",
  "Bremerhaven",
  "Koblenz",
  "Bergisch Gladbach",
  "Jena",
  "Remscheid",
  "Erlangen",
  "Moers",
  "Siegen",
  "Hildesheim",
  "Salzgitter",
  "Cottbus",
  "Bocholt",
]
